name: Deploy on DigitalOcean

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_SECRET_KEY }}
          script: |
            cd ~/api-server
            git pull origin prod

            docker compose up -d --build
            docker image prune -f
